//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftLauncher.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default player name.
        /// </summary>
        public static string DefaultPlayerName {
            get {
                return ResourceManager.GetString("DefaultPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fIles left.
        /// </summary>
        public static string DownloadFilesLeft {
            get {
                return ResourceManager.GetString("DownloadFilesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge.
        /// </summary>
        public static string Forge {
            get {
                return ResourceManager.GetString("Forge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge version.
        /// </summary>
        public static string ForgeVersion {
            get {
                return ResourceManager.GetString("ForgeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher visibility.
        /// </summary>
        public static string LauncherVisibility {
            get {
                return ResourceManager.GetString("LauncherVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft version.
        /// </summary>
        public static string MinecraftVersion {
            get {
                return ResourceManager.GetString("MinecraftVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile.
        /// </summary>
        public static string NewProfile {
            get {
                return ResourceManager.GetString("NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick directory.
        /// </summary>
        public static string PickDirectory {
            get {
                return ResourceManager.GetString("PickDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the Forge authors ❤️.
        /// </summary>
        public static string PleaseSupportForgeAuthors {
            get {
                return ResourceManager.GetString("PleaseSupportForgeAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch aborted.
        /// </summary>
        public static string ProgressAbort {
            get {
                return ResourceManager.GetString("ProgressAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download game files.
        /// </summary>
        public static string ProgressDownloadFiles {
            get {
                return ResourceManager.GetString("ProgressDownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game exited.
        /// </summary>
        public static string ProgressEnd {
            get {
                return ResourceManager.GetString("ProgressEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to start game.
        /// </summary>
        public static string ProgressFailToStartGame {
            get {
                return ResourceManager.GetString("ProgressFailToStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to install Forge.
        /// </summary>
        public static string ProgressForgeInstallFailed {
            get {
                return ResourceManager.GetString("ProgressForgeInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Forge.
        /// </summary>
        public static string ProgressInstallForge {
            get {
                return ResourceManager.GetString("ProgressInstallForge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid profile, check parameters.
        /// </summary>
        public static string ProgressInvalidProfile {
            get {
                return ResourceManager.GetString("ProgressInvalidProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading available minecraft versions.
        /// </summary>
        public static string ProgressLoading {
            get {
                return ResourceManager.GetString("ProgressLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare to start game.
        /// </summary>
        public static string ProgressPrepare {
            get {
                return ResourceManager.GetString("ProgressPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to launch!.
        /// </summary>
        public static string ProgressReady {
            get {
                return ResourceManager.GetString("ProgressReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game start.
        /// </summary>
        public static string ProgressStartGame {
            get {
                return ResourceManager.GetString("ProgressStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        public static string SaveProfile {
            get {
                return ResourceManager.GetString("SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps left.
        /// </summary>
        public static string StepsLeft {
            get {
                return ResourceManager.GetString("StepsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string StopGame {
            get {
                return ResourceManager.GetString("StopGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Launcher.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This drive not exist.
        /// </summary>
        public static string ValidationDirectoryDriveNotExist {
            get {
                return ResourceManager.GetString("ValidationDirectoryDriveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty folder in path is restricted.
        /// </summary>
        public static string ValidationDirectoryEmptyFolderInPath {
            get {
                return ResourceManager.GetString("ValidationDirectoryEmptyFolderInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        public static string ValidationDirectoryInvalidPath {
            get {
                return ResourceManager.GetString("ValidationDirectoryInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIrectory path cannot contain \ / : * ?  &quot; &lt; &gt; |.
        /// </summary>
        public static string ValidationDirectoryRestrictedChar {
            get {
                return ResourceManager.GetString("ValidationDirectoryRestrictedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty.
        /// </summary>
        public static string ValidationEmpty {
            get {
                return ResourceManager.GetString("ValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name can contain only letters, digit and underscore symbol.
        /// </summary>
        public static string ValidationPlayerNameRestrictedChar {
            get {
                return ResourceManager.GetString("ValidationPlayerNameRestrictedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name must be shorter.
        /// </summary>
        public static string ValidationPlayerNameTooLong {
            get {
                return ResourceManager.GetString("ValidationPlayerNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name must be longer.
        /// </summary>
        public static string ValidationPlayerNameTooShort {
            get {
                return ResourceManager.GetString("ValidationPlayerNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken.
        /// </summary>
        public static string ValidationRestrictedProfileName {
            get {
                return ResourceManager.GetString("ValidationRestrictedProfileName", resourceCulture);
            }
        }
    }
}
